"""add foreign keys to user_id columns

Revision ID: 52d4d8fb5cc9
Revises: 660e37e03a1f
Create Date: 2026-04-24 19:14:06.591547

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '52d4d8fb5cc9'
down_revision: Union[str, Sequence[str], None] = '660e37e03a1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'interests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reminders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'search_digests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profiles', type_='foreignkey')
    op.drop_constraint(None, 'search_digests', type_='foreignkey')
    op.drop_constraint(None, 'reminders', type_='foreignkey')
    op.drop_constraint(None, 'interests', type_='foreignkey')
    # ### end Alembic commands ###
