"""add session_summaries and estimated_tokens to user_profiles

Revision ID: 660e37e03a1f
Revises: 1701807c933a
Create Date: 2026-04-24 18:54:19.946644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '660e37e03a1f'
down_revision: Union[str, Sequence[str], None] = '1701807c933a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('session_summaries', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Array of session summaries (compressed on TTL expire)'))
    op.add_column('user_profiles', sa.Column('estimated_tokens', sa.Integer(), nullable=False, comment='Estimated token count for context monitoring'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'estimated_tokens')
    op.drop_column('user_profiles', 'session_summaries')
    # ### end Alembic commands ###
